name: Deploy expo updates ( development )

on:
  # Trigger: on new tag push
  push:
    branches:
      - development
    paths:
      - 'src/**'
      - '*.json'
      - '*.js'
      - '.github/**'

jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Checkout development
        run: git checkout development

      # Install frontend dependencies based on nvmrc
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Set Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install frontend dependencies
        run: npm i
      
      # Run the deployment scripts
      - name: Create environment files
        run: |
          echo -e "${{ secrets.DOTENV_DEVELOPMENT }}" > .env
          echo -e "${{ secrets.GOOGLE_SERVICES_JSON_DEVELOPMENT }}" > google-services-development.json
          echo -e "${{ secrets.GOOGLE_SERVICES_PLIST_DEVELOPMENT }}" > GoogleService-Info-development.plist

      # Automated testing
      - name: Automated testing
        run: npm run test:all

      - name: Testing failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos # or path/to/artifact

      - name: Send failure push notification
        if: ${{ failure() }}
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=X Nutshell Error&message=Development branch failed to deploy&url=https://github.com/nutshell-platform/app/actions&priority=1" https://api.pushover.net/1/messages.json
        
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}


      - name: Publish
        run: npm run deploy:development

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,storage,firestore --force --project=development
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Send success push notification
        run: curl -f -X POST -d "token=${{ secrets.PUSHOVER_TOKEN }}&user=${{ secrets.PUSHOVER_USER }}&title=Nutshell Deployed&message=Development branch is now live&url=https://beta.nutshell.social/&priority=1" https://api.pushover.net/1/messages.json