name: Deploy expo updates ( master )

on:
  # Trigger: on new tag push
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '*.json'
      - '*.js'
      - '.github/**'
      - 'functions/**'

jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
        working-directory: website

      - name: Set Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install frontend dependencies
        run: npm i

      - name: Install functions dependencies
        run: npm i
        working-directory: functions

      - name: Create environment files
        run: |
          echo -e "${{ secrets.DOTENV_PRODUCTION }}" > .env
          echo -e "${{ secrets.GOOGLE_SERVICES_JSON }}" > google-services.json
          echo -e "${{ secrets.GOOGLE_SERVICES_PLIST }}" > GoogleService-Info.plist
          

      - name: Automated testing
        run: npm run test:all

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}


      - name: Publish
        run: npm run deploy:production

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --force --project=production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}