name: Deploy expo updates ( master )

on:
  # Trigger: on new tag push
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '*.json'
      - '*.js'
      - '.github/**'
      - 'functions/*'

jobs:
  build:
    name: Publish changes

    runs-on: macos-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: installing node 13
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install dependencies
        run: |
          npm i
          npm i -g sharp-cli
          cd functions
          npm i
          cd ..

      - name: Create environment files
        run: |
          echo -e "${{ secrets.GOOGLE_SERVICES_JSON }}" > google-services.json
          echo -e "${{ secrets.DOTENV_PRODUCTION }}" > .env

      - name: Automated testing
        run: npm test -- --bail


      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}


      - name: Publish
        run: npm run publish

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --force --project=production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}