name: Deploy expo updates ( staging )

on:
  # Trigger: on new tag push
  push:
    branches:
      - staging
    paths:
      - 'src/**'
      - '*.json'
      - '*.js'
      - '.github/**'
      - 'functions/*'

jobs:
  build:
    name: Publish changes

    runs-on: ubuntu-latest

    steps:
      # Get the repo files from current commit
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Set right stageing area
        run: git checkout staging

      - name: installing node 13
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install dependencies
        run: |
          npm i
          npm i -g sharp-cli
          cd functions
          npm i
          cd ..


      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}


      - name: Publish
        run: |
          echo -e "${{ secrets.DOTENV_STAGING }}" > .env
          echo -e "${{ secrets.GOOGLE_SERVICES_JSON }}" > google-services.json
          npm run stage

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project=staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}